//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int PK_AuditLogId { get; set; }
        public string ActionType { get; set; }
        public string AffectedTable { get; set; }
        public string AuditDetails { get; set; }
        public Nullable<int> SysCreatedID { get; set; }
        public Nullable<System.DateTime> SysCreatedDate { get; set; }
    }
}
