//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogBreed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DogBreed()
        {
            this.SubBreeds = new HashSet<DogBreed>();
        }
    
        public int PK_DogBreedId { get; set; }
        public string DogName { get; set; }
        public Nullable<int> ParentBreedId { get; set; }
        public string Origin { get; set; }
        public string LifeSpan { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> SysCreatedDate { get; set; }
        public Nullable<int> SysCreatedID { get; set; }
        public Nullable<System.DateTime> SysModifiedDate { get; set; }
        public Nullable<int> SysModifiedID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogBreed> SubBreeds { get; set; }
        public virtual DogBreed ParentBreed { get; set; }
    }
}
