//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int PK_UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string AuthProvider { get; set; }
        public string AuthId { get; set; }
        public Nullable<System.DateTime> SysCreatedDate { get; set; }
        public Nullable<System.DateTime> SysModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
